version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000

  backend:
    build: ./Server
    ports:
      - 3001:3001
    environment:
      MONGODB_URI: mongodb://mongodb:27017/ProxiMap

  mongodb:
    image: mongo:latest
    container_name: proximap_mongodb

    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  data-seeder:
    build: ./DB
    depends_on:
      - mongodb


volumes:
  ProxiMap:
  mongodb_data: