version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000

  backend:
    build: ./Server
    ports:
      - 3001:3001
    environment:
      MONGODB_URI: mongodb://database:27017

  database:  
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ProxiMap:/data/db
volumes:
  ProxiMap: