# Use the official MongoDB image
FROM mongo:latest

# Optional: Copy any custom scripts or configurations
# COPY init-mongo.js /docker-entrypoint-initdb.d/

#COPY ./init-mongo.js /docker-entrypoint-initdb.d/
#      - ./USERS_DATA.js:/docker-entrypoint-initdb.d/USERS_DATA.js
 #     - ./CATEGORIES_DATA.js:/docker-entrypoint-initdb.d/CATEGORIES_DATA.js
 #     - ./SERVICES_DATA.js:/docker-entrypoint-initdb.d/SERVICES_DATA.js

# Expose the default MongoDB port
EXPOSE 27017
