# Use the official MongoDB image
FROM mongo:latest

# Optional: Copy any custom scripts or configurations
# COPY init-mongo.js /docker-entrypoint-initdb.d/

# Expose the default MongoDB port
EXPOSE 27017
