version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: proximap_mongodb
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
