version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: proximap_mongodb

    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  data-seeder:
    build: .
    depends_on:
      - mongodb

volumes:
  mongodb_data:
